dist: xenial

language: go

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get github.com/Telmate/proxmox-api-go
  - go install github.com/Telmate/proxmox-api-go
  - go get github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
  - go get github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox

script:
  - make
  - make install
